-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        files: \.(groovy|md|yaml)$
        args:
        - --no-markdown-linebreak-ext
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: remove-crlf
        files: \.(groovy|md|yaml)$
    -   id: remove-tabs
        files: \.(groovy|md|yaml)$
    -   id: insert-license
        files: \.groovy$
        args:
        - --license-filepath
        - src/LICENSE-short.txt
        - --comment-prefix
        - //
-   repo: local
    hooks:
    -   id: gradle-test
        name: Test unitaires Groovy
        language: system
        entry: sh -c 'gradle test'
        files: \.groovy$
-   repo: local
    hooks:
    -   id: forbid-abstract-classes-and-traits
        name: Ensure neither abstract classes nor traits are used
        language: pcre
        entry: "^(abstract|trait) "
        files: ^src/.*\.groovy$
    -   id: force-JsonSlurperClassic
        name: Ensure JsonSlurperClassic is used instead of non-serializable JsonSlurper
        language: pcre
        entry: JsonSlurper[^C]
        files: \.groovy$
    -   id: forbid-instanceof-string
        name: Use "instanceof CharSequence" to also support GString
        language: pcre
        entry: " instanceof G?String"
        files: \.groovy$