version: '2' 
services: 
  elasticsearch: 
    image: "elasticsearch:1.7" 
    command: "elasticsearch -Dcluster.name=hesperides" 
  redis: 
    image: "redis" 
  hesperides: 
    image: "hesperides/hesperides"
    ports: 
      - "8080:8080"
    depends_on:
      - elasticsearch
      - redis
